---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    service: app
spec:
  replicas: 5
  template:
    metadata:
      annotations:
        forceRedeployUniqId: "{{CF_REVISION}}"
      labels:
        service: app
    spec:
      containers:
      - image: r.cfcr.io/nikolai/demochat:k8-test
        name: app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
        - name: rcfcrsecret
