---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    service: app
